server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: api-gateway
        health-check-path: /actuator/health
        health-check-interval: 10s